name: "elk-auth-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
- type: filestream
  scan_frequency: 1s
  enabled: true
  paths:
    - /var/app/log/*
  tags: ["auth"]
  json:
    keys_under_root: true
    add_error_key: true

  processors:
    - decode_json_fields:
        fields: ["message"]
        process_array: false
        max_depth: 2
        target: ""
        overwrite_keys: true
        add_error_key: false

output.logstash:
  enabled: true
  hosts: ["${ELK_LOGSTASH_HOST}:${ELK_LOGSTASH_PORT}"]